/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#003d9b',
          light: '#0052CC',
          container: '#dae2ff',
          fixed: '#dae2ff',
          on: '#FFFFFF',
          'on-container': '#001a41',
          'on-fixed': '#001a41',
        },
        'medical-blue': {
          DEFAULT: '#003d9b',
          dark: '#002366',
          light: '#b2c5ff',
        },
        secondary: {
          DEFAULT: '#5d5f5f',
          container: '#dfe0e0',
          on: '#FFFFFF',
        },
        tertiary: {
          DEFAULT: '#7b2600',
          fixed: '#ffdad6',
          on: '#FFFFFF',
          'on-container': '#311000',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          on: '#FFFFFF',
        },
        surface: {
          DEFAULT: '#faf8ff',
          dim: '#d9d9e4',
          container: '#ededf8',
          'container-low': '#f3f3fd',
          'container-lowest': '#ffffff',
          'container-high': '#e7e7f2',
          'container-highest': '#e1e2ec',
        },
        outline: {
          DEFAULT: '#737685',
          variant: '#c3c6d6',
        },
        'on-surface': {
          DEFAULT: '#191b23',
          variant: '#434654',
        },
        status: {
          green: '#166534',
          'green-light': '#dcfce7',
          red: '#ba1a1a',
          'red-light': '#fef2f2',
          orange: '#b45309',
          'orange-light': '#fef3c7',
          amber: '#d97706',
          'amber-light': '#fef3c7',
          blue: '#1d4ed8',
          'blue-light': '#dbeafe',
          teal: '#008B8B',
          'teal-light': '#d1fae5',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '24px',
        'margin': '32px',
        'edge-margin': '16px',
        'touch-target': '44px',
      },
      borderRadius: {
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'level-0': 'none',
        'level-1': '0px 2px 4px rgba(0,0,0,0.05)',
        'level-2': '0px 12px 24px rgba(0,82,204,0.1)',
        'card': '0px 2px 4px rgba(0,0,0,0.05)',
        'nav-up': '0px -4px 12px rgba(0,0,0,0.05)',
      },
      minHeight: {
        'touch': '44px',
      },
      minWidth: {
        'touch': '44px',
      },
      screens: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}
